### ISSUE TITLE
Evaluate - Frameworks for Automated Testing on GitHub

### ISSUE THREAD

**Issue by kreynen** [cu-uis/cu-starterkit-project#5]
With all of the changes related to https://github.com/cu-uis/cu-starterkit-project/issues/3 and https://github.com/cu-uis/cu-starterkit-project/issues/4 happening in the next year as we move to 9.3.x -> 9.4.x -> 10.0.x, we've agreed to prioritize addressing the need for some level of automated testing now. 

https://mglaman.medium.com/github-actions-has-made-continuous-integration-seamless-73cd45a1f495
https://mglaman.dev/blog/github-action-setting-drupal-testing
https://drupalize.me/blog/run-integration-tests-tugboat-and-github-actions
https://jet.dev/blog/coding-standards-phpcs-drupal-github-actions/

https://www.lullabot.com/articles/continuous-deployment-infrastructure-code-and-drupal-part-1
https://www.lullabot.com/articles/continuous-deployment-infrastructure-code-and-drupal-part-2
https://github.com/Lullabot/drupal9ci#github-actions

https://drupal.tv/external-video/2020-03-21/github-actions-action (no really about Drupal/PHP, but good overview of why Actions are better than full CI in many cases).

I'm sure @alexfinnarn has more thoughts on this.

**Comment by alexfinnarn** [comment]
I certainly do have opinions on this and still recommend using Cypress and writing functional-level tests in lieu of lower-level testing. Since the starterkit is for creating sites, it's different than testing a deployed application with custom code, but I think Drupal core is still a "product" you can test after installation just like this starterkit. 

For a Drupal project running on Heroku, I set up the following workflow, which saves GitHub Action minutes by decoupling the build from test run:

- build the application on whatever hosting service you use. Pantheon has multidev, Heroku has review apps, and other hosts have similar features. Heroku automagically built the Drupal app I'm referencing, but with Pantheon, I'm guessing a GH action/workflow could be developed with Terminus.
- At the end of the build, use curl to trigger a GH webhook. I used Drupal for this, but you can do it in all in bash/shell: `curl https://my.site.com/api/review-apps/${HEROKU_APP_NAME}/${HEROKU_BRANCH}`
- (Optional) Have an application take the curl information and connect to GH: 
```php
  public function reviewApps(string $name, string $branch): JsonResponse {
    $data = json_encode([
      'event_type' => "heroku-ci",
      'client_payload' => [
        'app_url' => "https://$name.herokuapp.com",
        'branch' => "feature/$branch",
      ],
    ]);

    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, 'https://api.github.com/repos/my-org/my-repo/dispatches');
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
      'Authorization: Token ' . getenv('YOUR_GITHUB_TOKEN'),
      'User-agent: Drupal',
    ]);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
    $result = curl_exec($ch);

    return new JsonResponse($result, 200);
  }
```
- Use Cypress GH Action to run tests with appropriate `baseURL`

```yaml
name: Cypress Tests
on:
  repository_dispatch:
    types:
      - heroku-ci
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.branch }}

      - name: Cypress run
        env:
          CYPRESS_CE_USER: ${{ secrets.CYPRESS_CE_USER }}
          CYPRESS_CE_PASS: ${{ secrets.CYPRESS_CE_PASS }}
          CYPRESS_BASE_URL: ${{ github.event.client_payload.app_url }}
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/real/**/*
```

I got that setup working, but if your host creates QA environments based on the branch name, you can skip a lot of steps and just wait for the app to build...something like the Web Express script that used the shell command to check if a route returned a 200 response and then started testing.

At the end of the day, I think Drupal + Solr + whatever is too big to handle well trying to replicate the environment totally within GH CI tools. Plus, you're not actually testing your application at that point. You're just testing a replica...and the idea of "well it's more isolated and pure wholly in GH" is laughable to me since you need so many dependencies. For smaller node.js apps, I just build the app in GH CI with the test run, but I've had trouble maintaining all the dependencies with a typical Drupal production setup.

So without standardizing on a host, I'd just provide guidance for starterkit users.
